language: php
cache: false

sudo: false

php:
  - 5.6
  - nightly
  - hhvm

before_script:
  - composer install

script:
  - ./vendor/bin/phpunit --disallow-test-output --report-useless-tests --coverage-clover ./clover.xml --group=Coverage
  - ./vendor/bin/phpunit --disallow-test-output --report-useless-tests --exclude-group=Coverage
  - ./vendor/bin/phpcs --standard=PSR2 ./src/ ./tests/
  - ./vendor/bin/phpstan analyse -c phpstan.neon -l 5 src
  - ./vendor/bin/phpstan analyse -c phpstan.tests.neon -l 4 tests

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly
    