language: php
cache: false

sudo: false

php:
  - 7.1
  - nightly
  - hhvm

before_script:
  - composer install

script:
  - ./vendor/bin/phpunit --disallow-test-output --report-useless-tests --coverage-clover ./clover.xml --group=Coverage
  - ./vendor/bin/phpunit --disallow-test-output --report-useless-tests --exclude-group=Coverage
  - ./vendor/bin/phpcs --standard=PSR2 ./src/ ./tests/

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: nightly
    