language: php
cache: false

sudo: false

php:
  - 7.1
  - nightly
  - hhvm

before_script:
  - composer install
  - composer update
  
script:
  - mkdir -p build/logs
  - ./vendor/bin/phpunit --disallow-test-output --report-useless-tests --coverage-clover ./clover.xml --group=Coverage
  - ./vendor/bin/phpunit --disallow-test-output --report-useless-tests --exclude-group=Coverage
  - ./vendor/bin/phpcs --standard=PSR2 ./src/ ./tests/

after_script:
  - php vendor/bin/coveralls -v

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: nightly
    